package mimemail

import (
	"net/textproto"
	"strings"
)

// Message is a parsed MIME message or a node in its MIME tree.
type Message struct {
	// Header contains the original, folded-decoded header fields.
	Header textproto.MIMEHeader

	// Root is the decoded MIME tree. Encode uses Root for content headers and
	// Header for message-level fields such as Subject, From, and To.
	Root *Part
}

// Part is either a leaf carrying Body or a multipart node carrying Parts.
type Part struct {
	// Header contains fields other than the content fields generated by Encode.
	Header textproto.MIMEHeader

	// Type is the lower-cased media type, for example text/plain.
	Type string

	// TypeParams contains Content-Type parameters except boundary.
	TypeParams map[string]string

	// Disposition is the lower-cased Content-Disposition value.
	Disposition string

	FileName  string
	ContentID string

	// Body is the transfer-decoded leaf body. It is nil for multipart nodes.
	Body []byte

	// Parts contains multipart children in their original order.
	Parts []*Part
}

func (p *Part) IsMultipart() bool {
	return len(p.Parts) > 0 || strings.HasPrefix(strings.ToLower(p.Type), "multipart/")
}
